import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_webrtc/flutter_webrtc.dart';
import 'websocket_service.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: LiveStreamPage(),
    );
  }
}

class LiveStreamPage extends StatefulWidget {
  const LiveStreamPage({super.key});

  @override
  _LiveStreamPageState createState() => _LiveStreamPageState();
}

class _LiveStreamPageState extends State<LiveStreamPage> {
  final WebSocketService socketService = WebSocketService();
  final RTCVideoRenderer _localRenderer = RTCVideoRenderer();
  final RTCVideoRenderer _remoteRenderer = RTCVideoRenderer();
  RTCPeerConnection? _peerConnection;
  bool isHost = false; // Change this to true if the user is the host
  String streamNumber = ''; // Stream number assigned to the host
  final TextEditingController _streamNumberController = TextEditingController();

  @override
  void initState() {
    super.initState();
    socketService.connect('ws://localhost:8080'); // Connect to WebSocket server

    // Listen to WebSocket messages
    socketService.messages.listen((data) {
      final message = data.toString();
      if (message.contains('offer')) {
        handleOffer(message);
      } else if (message.contains('answer')) {
        handleAnswer(message);
      } else if (message.contains('candidate')) {
        handleCandidate(message);
      }
    });

    initializeWebRTC();
  }

  // Initialize the WebRTC setup (local renderer for host side)
  Future<void> initializeWebRTC() async {
    await _localRenderer.initialize();
    await _remoteRenderer.initialize();

    // Initialize local camera and microphone
    MediaStream stream = await navigator.mediaDevices
        .getUserMedia({'video': true, 'audio': true});
    _localRenderer.srcObject = stream;

    // Create a PeerConnection
    _peerConnection = await createPeerConnection({
      'iceServers': [
        {'urls': 'stun:stun.l.google.com:19302'}
      ],
    });

    _peerConnection!.addStream(stream);
  }

  // Handle Offer received from the host (for the viewer)
  void handleOffer(String offer) async {
    await _peerConnection!
        .setRemoteDescription(RTCSessionDescription(offer, 'offer'));

    // Create an answer
    RTCSessionDescription answer = await _peerConnection!.createAnswer();
    await _peerConnection!.setLocalDescription(answer);

    // Send the answer to the host via WebSocket
    socketService.send(json.encode({
      'type': 'answer',
      'sdp': answer.sdp,
      'streamNumber': streamNumber,
    }));
  }

  // Handle Answer received from the viewer
  void handleAnswer(String answer) async {
    await _peerConnection!
        .setRemoteDescription(RTCSessionDescription(answer, 'answer'));
  }

  // Handle ICE candidates from the host and viewer
  void handleCandidate(String candidate) async {
    var candidateMap = json.decode(candidate);
    RTCIceCandidate iceCandidate = RTCIceCandidate(
      candidateMap['candidate'],
      candidateMap['sdpMid'],
      candidateMap['sdpMLineIndex'] as int?,
    );
    await _peerConnection!.addCandidate(iceCandidate);
  }

  @override
  void dispose() {
    _localRenderer.dispose();
    _remoteRenderer.dispose();
    socketService.disconnect();
    super.dispose();
  }

  // Function to start the live stream as the host
  void startLiveStream() {
    // Generate a unique stream number (this could also be generated by the server)
    streamNumber = DateTime.now().millisecondsSinceEpoch.toString();
    // Create an offer and send it to the WebSocket server with the stream number
    _peerConnection!.createOffer().then((offer) {
      _peerConnection!.setLocalDescription(offer);
      socketService.send(json.encode({
        'type': 'offer',
        'sdp': offer.sdp,
        'streamNumber': streamNumber,
      }));
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Live Streaming App")),
      body: Column(
        children: [
          // Local stream (host video)
          Expanded(child: RTCVideoView(_localRenderer)),

          // Remote stream (viewer video - to see the host's stream)
          Expanded(child: RTCVideoView(_remoteRenderer)),

          // For host or viewer to start or join a stream
          if (isHost)
            ElevatedButton(
              onPressed: startLiveStream, // Start live stream as host
              child: const Text('Start Live Stream'),
            )
          else
            Column(
              children: [
                TextField(
                  controller: _streamNumberController,
                  decoration: const InputDecoration(
                    labelText: 'Enter Stream Number to Join',
                  ),
                ),
                ElevatedButton(
                  onPressed: () {
                    // Join the live stream as viewer
                    streamNumber = _streamNumberController.text;
                    socketService.send(json.encode({
                      'type': 'join',
                      'streamNumber': streamNumber,
                    }));
                  },
                  child: const Text('Join Live Stream'),
                ),
              ],
            ),

          // Button to toggle between host and viewer
          ElevatedButton(
            onPressed: () {
              setState(() {
                isHost = !isHost; // Toggle between host and viewer
              });
            },
            child: Text(isHost ? 'Switch to Viewer' : 'Switch to Host'),
          ),
        ],
      ),
    );
  }
}
